// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: standard_cyborg/proto/sc3d/point_cloud.proto

#include "standard_cyborg/proto/sc3d/point_cloud.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_standard_5fcyborg_2fproto_2fmath_2ftensor_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Tensor_standard_5fcyborg_2fproto_2fmath_2ftensor_2eproto;
namespace standard_cyborg {
namespace proto {
namespace sc3d {
class PointCloudDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PointCloud> _instance;
} _PointCloud_default_instance_;
}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg
static void InitDefaultsscc_info_PointCloud_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::standard_cyborg::proto::sc3d::_PointCloud_default_instance_;
    new (ptr) ::standard_cyborg::proto::sc3d::PointCloud();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::standard_cyborg::proto::sc3d::PointCloud::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_PointCloud_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_PointCloud_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto}, {
      &scc_info_Tensor_standard_5fcyborg_2fproto_2fmath_2ftensor_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::PointCloud, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::PointCloud, frame_),
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::PointCloud, positions_),
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::PointCloud, normals_),
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::PointCloud, colors_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::standard_cyborg::proto::sc3d::PointCloud)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::standard_cyborg::proto::sc3d::_PointCloud_default_instance_),
};

const char descriptor_table_protodef_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n,standard_cyborg/proto/sc3d/point_cloud"
  ".proto\022\032standard_cyborg.proto.sc3d\032\'stan"
  "dard_cyborg/proto/math/tensor.proto\"\273\001\n\n"
  "PointCloud\022\r\n\005frame\030\001 \001(\t\0225\n\tpositions\030\002"
  " \001(\0132\".standard_cyborg.proto.math.Tensor"
  "\0223\n\007normals\030\003 \001(\0132\".standard_cyborg.prot"
  "o.math.Tensor\0222\n\006colors\030\004 \001(\0132\".standard"
  "_cyborg.proto.math.Tensorb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto_deps[1] = {
  &::descriptor_table_standard_5fcyborg_2fproto_2fmath_2ftensor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto_sccs[1] = {
  &scc_info_PointCloud_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto_once;
static bool descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto = {
  &descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto_initialized, descriptor_table_protodef_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto, "standard_cyborg/proto/sc3d/point_cloud.proto", 313,
  &descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto_once, descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto_sccs, descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto::offsets,
  file_level_metadata_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto, 1, file_level_enum_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto, file_level_service_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto), true);
namespace standard_cyborg {
namespace proto {
namespace sc3d {

// ===================================================================

void PointCloud::InitAsDefaultInstance() {
  ::standard_cyborg::proto::sc3d::_PointCloud_default_instance_._instance.get_mutable()->positions_ = const_cast< ::standard_cyborg::proto::math::Tensor*>(
      ::standard_cyborg::proto::math::Tensor::internal_default_instance());
  ::standard_cyborg::proto::sc3d::_PointCloud_default_instance_._instance.get_mutable()->normals_ = const_cast< ::standard_cyborg::proto::math::Tensor*>(
      ::standard_cyborg::proto::math::Tensor::internal_default_instance());
  ::standard_cyborg::proto::sc3d::_PointCloud_default_instance_._instance.get_mutable()->colors_ = const_cast< ::standard_cyborg::proto::math::Tensor*>(
      ::standard_cyborg::proto::math::Tensor::internal_default_instance());
}
class PointCloud::_Internal {
 public:
  static const ::standard_cyborg::proto::math::Tensor& positions(const PointCloud* msg);
  static const ::standard_cyborg::proto::math::Tensor& normals(const PointCloud* msg);
  static const ::standard_cyborg::proto::math::Tensor& colors(const PointCloud* msg);
};

const ::standard_cyborg::proto::math::Tensor&
PointCloud::_Internal::positions(const PointCloud* msg) {
  return *msg->positions_;
}
const ::standard_cyborg::proto::math::Tensor&
PointCloud::_Internal::normals(const PointCloud* msg) {
  return *msg->normals_;
}
const ::standard_cyborg::proto::math::Tensor&
PointCloud::_Internal::colors(const PointCloud* msg) {
  return *msg->colors_;
}
void PointCloud::clear_positions() {
  if (GetArenaNoVirtual() == nullptr && positions_ != nullptr) {
    delete positions_;
  }
  positions_ = nullptr;
}
void PointCloud::clear_normals() {
  if (GetArenaNoVirtual() == nullptr && normals_ != nullptr) {
    delete normals_;
  }
  normals_ = nullptr;
}
void PointCloud::clear_colors() {
  if (GetArenaNoVirtual() == nullptr && colors_ != nullptr) {
    delete colors_;
  }
  colors_ = nullptr;
}
PointCloud::PointCloud()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:standard_cyborg.proto.sc3d.PointCloud)
}
PointCloud::PointCloud(const PointCloud& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  frame_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_frame().empty()) {
    frame_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.frame_);
  }
  if (from._internal_has_positions()) {
    positions_ = new ::standard_cyborg::proto::math::Tensor(*from.positions_);
  } else {
    positions_ = nullptr;
  }
  if (from._internal_has_normals()) {
    normals_ = new ::standard_cyborg::proto::math::Tensor(*from.normals_);
  } else {
    normals_ = nullptr;
  }
  if (from._internal_has_colors()) {
    colors_ = new ::standard_cyborg::proto::math::Tensor(*from.colors_);
  } else {
    colors_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:standard_cyborg.proto.sc3d.PointCloud)
}

void PointCloud::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PointCloud_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto.base);
  frame_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&positions_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&colors_) -
      reinterpret_cast<char*>(&positions_)) + sizeof(colors_));
}

PointCloud::~PointCloud() {
  // @@protoc_insertion_point(destructor:standard_cyborg.proto.sc3d.PointCloud)
  SharedDtor();
}

void PointCloud::SharedDtor() {
  frame_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete positions_;
  if (this != internal_default_instance()) delete normals_;
  if (this != internal_default_instance()) delete colors_;
}

void PointCloud::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PointCloud& PointCloud::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PointCloud_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_2eproto.base);
  return *internal_default_instance();
}


void PointCloud::Clear() {
// @@protoc_insertion_point(message_clear_start:standard_cyborg.proto.sc3d.PointCloud)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  frame_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && positions_ != nullptr) {
    delete positions_;
  }
  positions_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && normals_ != nullptr) {
    delete normals_;
  }
  normals_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && colors_ != nullptr) {
    delete colors_;
  }
  colors_ = nullptr;
  _internal_metadata_.Clear();
}

const char* PointCloud::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string frame = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_frame();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "standard_cyborg.proto.sc3d.PointCloud.frame"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .standard_cyborg.proto.math.Tensor positions = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_positions(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .standard_cyborg.proto.math.Tensor normals = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_normals(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .standard_cyborg.proto.math.Tensor colors = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_colors(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PointCloud::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:standard_cyborg.proto.sc3d.PointCloud)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string frame = 1;
  if (this->frame().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_frame().data(), static_cast<int>(this->_internal_frame().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "standard_cyborg.proto.sc3d.PointCloud.frame");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_frame(), target);
  }

  // .standard_cyborg.proto.math.Tensor positions = 2;
  if (this->has_positions()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::positions(this), target, stream);
  }

  // .standard_cyborg.proto.math.Tensor normals = 3;
  if (this->has_normals()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::normals(this), target, stream);
  }

  // .standard_cyborg.proto.math.Tensor colors = 4;
  if (this->has_colors()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::colors(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:standard_cyborg.proto.sc3d.PointCloud)
  return target;
}

size_t PointCloud::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:standard_cyborg.proto.sc3d.PointCloud)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string frame = 1;
  if (this->frame().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_frame());
  }

  // .standard_cyborg.proto.math.Tensor positions = 2;
  if (this->has_positions()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *positions_);
  }

  // .standard_cyborg.proto.math.Tensor normals = 3;
  if (this->has_normals()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *normals_);
  }

  // .standard_cyborg.proto.math.Tensor colors = 4;
  if (this->has_colors()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *colors_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PointCloud::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:standard_cyborg.proto.sc3d.PointCloud)
  GOOGLE_DCHECK_NE(&from, this);
  const PointCloud* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PointCloud>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:standard_cyborg.proto.sc3d.PointCloud)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:standard_cyborg.proto.sc3d.PointCloud)
    MergeFrom(*source);
  }
}

void PointCloud::MergeFrom(const PointCloud& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:standard_cyborg.proto.sc3d.PointCloud)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.frame().size() > 0) {

    frame_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.frame_);
  }
  if (from.has_positions()) {
    _internal_mutable_positions()->::standard_cyborg::proto::math::Tensor::MergeFrom(from._internal_positions());
  }
  if (from.has_normals()) {
    _internal_mutable_normals()->::standard_cyborg::proto::math::Tensor::MergeFrom(from._internal_normals());
  }
  if (from.has_colors()) {
    _internal_mutable_colors()->::standard_cyborg::proto::math::Tensor::MergeFrom(from._internal_colors());
  }
}

void PointCloud::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:standard_cyborg.proto.sc3d.PointCloud)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PointCloud::CopyFrom(const PointCloud& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:standard_cyborg.proto.sc3d.PointCloud)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PointCloud::IsInitialized() const {
  return true;
}

void PointCloud::InternalSwap(PointCloud* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  frame_.Swap(&other->frame_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(positions_, other->positions_);
  swap(normals_, other->normals_);
  swap(colors_, other->colors_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PointCloud::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::standard_cyborg::proto::sc3d::PointCloud* Arena::CreateMaybeMessage< ::standard_cyborg::proto::sc3d::PointCloud >(Arena* arena) {
  return Arena::CreateInternal< ::standard_cyborg::proto::sc3d::PointCloud >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
