// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: standard_cyborg/proto/sc3d/polygon_label_multi.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "standard_cyborg/proto/math/core.pb.h"
#include "standard_cyborg/proto/sc3d/qc_status.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto;
namespace standard_cyborg {
namespace proto {
namespace sc3d {
class PolygonLabelMulti;
class PolygonLabelMultiDefaultTypeInternal;
extern PolygonLabelMultiDefaultTypeInternal _PolygonLabelMulti_default_instance_;
class PolygonLabelMulti_PolygonLabel;
class PolygonLabelMulti_PolygonLabelDefaultTypeInternal;
extern PolygonLabelMulti_PolygonLabelDefaultTypeInternal _PolygonLabelMulti_PolygonLabel_default_instance_;
class PolygonLabelMulti_SubPolygon;
class PolygonLabelMulti_SubPolygonDefaultTypeInternal;
extern PolygonLabelMulti_SubPolygonDefaultTypeInternal _PolygonLabelMulti_SubPolygon_default_instance_;
}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg
PROTOBUF_NAMESPACE_OPEN
template<> ::standard_cyborg::proto::sc3d::PolygonLabelMulti* Arena::CreateMaybeMessage<::standard_cyborg::proto::sc3d::PolygonLabelMulti>(Arena*);
template<> ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel* Arena::CreateMaybeMessage<::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel>(Arena*);
template<> ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon* Arena::CreateMaybeMessage<::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace standard_cyborg {
namespace proto {
namespace sc3d {

// ===================================================================

class PolygonLabelMulti_SubPolygon :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon) */ {
 public:
  PolygonLabelMulti_SubPolygon();
  virtual ~PolygonLabelMulti_SubPolygon();

  PolygonLabelMulti_SubPolygon(const PolygonLabelMulti_SubPolygon& from);
  PolygonLabelMulti_SubPolygon(PolygonLabelMulti_SubPolygon&& from) noexcept
    : PolygonLabelMulti_SubPolygon() {
    *this = ::std::move(from);
  }

  inline PolygonLabelMulti_SubPolygon& operator=(const PolygonLabelMulti_SubPolygon& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolygonLabelMulti_SubPolygon& operator=(PolygonLabelMulti_SubPolygon&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PolygonLabelMulti_SubPolygon& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PolygonLabelMulti_SubPolygon* internal_default_instance() {
    return reinterpret_cast<const PolygonLabelMulti_SubPolygon*>(
               &_PolygonLabelMulti_SubPolygon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PolygonLabelMulti_SubPolygon& a, PolygonLabelMulti_SubPolygon& b) {
    a.Swap(&b);
  }
  inline void Swap(PolygonLabelMulti_SubPolygon* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PolygonLabelMulti_SubPolygon* New() const final {
    return CreateMaybeMessage<PolygonLabelMulti_SubPolygon>(nullptr);
  }

  PolygonLabelMulti_SubPolygon* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PolygonLabelMulti_SubPolygon>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PolygonLabelMulti_SubPolygon& from);
  void MergeFrom(const PolygonLabelMulti_SubPolygon& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolygonLabelMulti_SubPolygon* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto);
    return ::descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionsFieldNumber = 1,
    kFlagFieldNumber = 2,
  };
  // repeated .standard_cyborg.proto.math.Vec2 positions = 1;
  int positions_size() const;
  private:
  int _internal_positions_size() const;
  public:
  void clear_positions();
  ::standard_cyborg::proto::math::Vec2* mutable_positions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::math::Vec2 >*
      mutable_positions();
  private:
  const ::standard_cyborg::proto::math::Vec2& _internal_positions(int index) const;
  ::standard_cyborg::proto::math::Vec2* _internal_add_positions();
  public:
  const ::standard_cyborg::proto::math::Vec2& positions(int index) const;
  ::standard_cyborg::proto::math::Vec2* add_positions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::math::Vec2 >&
      positions() const;

  // bool flag = 2;
  void clear_flag();
  bool flag() const;
  void set_flag(bool value);
  private:
  bool _internal_flag() const;
  void _internal_set_flag(bool value);
  public:

  // @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::math::Vec2 > positions_;
  bool flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto;
};
// -------------------------------------------------------------------

class PolygonLabelMulti_PolygonLabel :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel) */ {
 public:
  PolygonLabelMulti_PolygonLabel();
  virtual ~PolygonLabelMulti_PolygonLabel();

  PolygonLabelMulti_PolygonLabel(const PolygonLabelMulti_PolygonLabel& from);
  PolygonLabelMulti_PolygonLabel(PolygonLabelMulti_PolygonLabel&& from) noexcept
    : PolygonLabelMulti_PolygonLabel() {
    *this = ::std::move(from);
  }

  inline PolygonLabelMulti_PolygonLabel& operator=(const PolygonLabelMulti_PolygonLabel& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolygonLabelMulti_PolygonLabel& operator=(PolygonLabelMulti_PolygonLabel&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PolygonLabelMulti_PolygonLabel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PolygonLabelMulti_PolygonLabel* internal_default_instance() {
    return reinterpret_cast<const PolygonLabelMulti_PolygonLabel*>(
               &_PolygonLabelMulti_PolygonLabel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PolygonLabelMulti_PolygonLabel& a, PolygonLabelMulti_PolygonLabel& b) {
    a.Swap(&b);
  }
  inline void Swap(PolygonLabelMulti_PolygonLabel* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PolygonLabelMulti_PolygonLabel* New() const final {
    return CreateMaybeMessage<PolygonLabelMulti_PolygonLabel>(nullptr);
  }

  PolygonLabelMulti_PolygonLabel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PolygonLabelMulti_PolygonLabel>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PolygonLabelMulti_PolygonLabel& from);
  void MergeFrom(const PolygonLabelMulti_PolygonLabel& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolygonLabelMulti_PolygonLabel* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto);
    return ::descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubPolygonsFieldNumber = 3,
  };
  // repeated .standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon subPolygons = 3;
  int subpolygons_size() const;
  private:
  int _internal_subpolygons_size() const;
  public:
  void clear_subpolygons();
  ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon* mutable_subpolygons(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon >*
      mutable_subpolygons();
  private:
  const ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon& _internal_subpolygons(int index) const;
  ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon* _internal_add_subpolygons();
  public:
  const ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon& subpolygons(int index) const;
  ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon* add_subpolygons();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon >&
      subpolygons() const;

  // @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon > subpolygons_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto;
};
// -------------------------------------------------------------------

class PolygonLabelMulti :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:standard_cyborg.proto.sc3d.PolygonLabelMulti) */ {
 public:
  PolygonLabelMulti();
  virtual ~PolygonLabelMulti();

  PolygonLabelMulti(const PolygonLabelMulti& from);
  PolygonLabelMulti(PolygonLabelMulti&& from) noexcept
    : PolygonLabelMulti() {
    *this = ::std::move(from);
  }

  inline PolygonLabelMulti& operator=(const PolygonLabelMulti& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolygonLabelMulti& operator=(PolygonLabelMulti&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PolygonLabelMulti& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PolygonLabelMulti* internal_default_instance() {
    return reinterpret_cast<const PolygonLabelMulti*>(
               &_PolygonLabelMulti_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PolygonLabelMulti& a, PolygonLabelMulti& b) {
    a.Swap(&b);
  }
  inline void Swap(PolygonLabelMulti* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PolygonLabelMulti* New() const final {
    return CreateMaybeMessage<PolygonLabelMulti>(nullptr);
  }

  PolygonLabelMulti* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PolygonLabelMulti>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PolygonLabelMulti& from);
  void MergeFrom(const PolygonLabelMulti& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolygonLabelMulti* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "standard_cyborg.proto.sc3d.PolygonLabelMulti";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto);
    return ::descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef PolygonLabelMulti_SubPolygon SubPolygon;
  typedef PolygonLabelMulti_PolygonLabel PolygonLabel;

  // accessors -------------------------------------------------------

  enum : int {
    kPolygonLabelsFieldNumber = 4,
    kScImagePathFieldNumber = 5,
    kQcStatusFieldNumber = 6,
  };
  // repeated .standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel polygonLabels = 4;
  int polygonlabels_size() const;
  private:
  int _internal_polygonlabels_size() const;
  public:
  void clear_polygonlabels();
  ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel* mutable_polygonlabels(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel >*
      mutable_polygonlabels();
  private:
  const ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel& _internal_polygonlabels(int index) const;
  ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel* _internal_add_polygonlabels();
  public:
  const ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel& polygonlabels(int index) const;
  ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel* add_polygonlabels();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel >&
      polygonlabels() const;

  // string scImagePath = 5;
  void clear_scimagepath();
  const std::string& scimagepath() const;
  void set_scimagepath(const std::string& value);
  void set_scimagepath(std::string&& value);
  void set_scimagepath(const char* value);
  void set_scimagepath(const char* value, size_t size);
  std::string* mutable_scimagepath();
  std::string* release_scimagepath();
  void set_allocated_scimagepath(std::string* scimagepath);
  private:
  const std::string& _internal_scimagepath() const;
  void _internal_set_scimagepath(const std::string& value);
  std::string* _internal_mutable_scimagepath();
  public:

  // .standard_cyborg.proto.sc3d.QcStatus qcStatus = 6;
  void clear_qcstatus();
  ::standard_cyborg::proto::sc3d::QcStatus qcstatus() const;
  void set_qcstatus(::standard_cyborg::proto::sc3d::QcStatus value);
  private:
  ::standard_cyborg::proto::sc3d::QcStatus _internal_qcstatus() const;
  void _internal_set_qcstatus(::standard_cyborg::proto::sc3d::QcStatus value);
  public:

  // @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.PolygonLabelMulti)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel > polygonlabels_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr scimagepath_;
  int qcstatus_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PolygonLabelMulti_SubPolygon

// repeated .standard_cyborg.proto.math.Vec2 positions = 1;
inline int PolygonLabelMulti_SubPolygon::_internal_positions_size() const {
  return positions_.size();
}
inline int PolygonLabelMulti_SubPolygon::positions_size() const {
  return _internal_positions_size();
}
inline ::standard_cyborg::proto::math::Vec2* PolygonLabelMulti_SubPolygon::mutable_positions(int index) {
  // @@protoc_insertion_point(field_mutable:standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon.positions)
  return positions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::math::Vec2 >*
PolygonLabelMulti_SubPolygon::mutable_positions() {
  // @@protoc_insertion_point(field_mutable_list:standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon.positions)
  return &positions_;
}
inline const ::standard_cyborg::proto::math::Vec2& PolygonLabelMulti_SubPolygon::_internal_positions(int index) const {
  return positions_.Get(index);
}
inline const ::standard_cyborg::proto::math::Vec2& PolygonLabelMulti_SubPolygon::positions(int index) const {
  // @@protoc_insertion_point(field_get:standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon.positions)
  return _internal_positions(index);
}
inline ::standard_cyborg::proto::math::Vec2* PolygonLabelMulti_SubPolygon::_internal_add_positions() {
  return positions_.Add();
}
inline ::standard_cyborg::proto::math::Vec2* PolygonLabelMulti_SubPolygon::add_positions() {
  // @@protoc_insertion_point(field_add:standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon.positions)
  return _internal_add_positions();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::math::Vec2 >&
PolygonLabelMulti_SubPolygon::positions() const {
  // @@protoc_insertion_point(field_list:standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon.positions)
  return positions_;
}

// bool flag = 2;
inline void PolygonLabelMulti_SubPolygon::clear_flag() {
  flag_ = false;
}
inline bool PolygonLabelMulti_SubPolygon::_internal_flag() const {
  return flag_;
}
inline bool PolygonLabelMulti_SubPolygon::flag() const {
  // @@protoc_insertion_point(field_get:standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon.flag)
  return _internal_flag();
}
inline void PolygonLabelMulti_SubPolygon::_internal_set_flag(bool value) {
  
  flag_ = value;
}
inline void PolygonLabelMulti_SubPolygon::set_flag(bool value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon.flag)
}

// -------------------------------------------------------------------

// PolygonLabelMulti_PolygonLabel

// repeated .standard_cyborg.proto.sc3d.PolygonLabelMulti.SubPolygon subPolygons = 3;
inline int PolygonLabelMulti_PolygonLabel::_internal_subpolygons_size() const {
  return subpolygons_.size();
}
inline int PolygonLabelMulti_PolygonLabel::subpolygons_size() const {
  return _internal_subpolygons_size();
}
inline void PolygonLabelMulti_PolygonLabel::clear_subpolygons() {
  subpolygons_.Clear();
}
inline ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon* PolygonLabelMulti_PolygonLabel::mutable_subpolygons(int index) {
  // @@protoc_insertion_point(field_mutable:standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel.subPolygons)
  return subpolygons_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon >*
PolygonLabelMulti_PolygonLabel::mutable_subpolygons() {
  // @@protoc_insertion_point(field_mutable_list:standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel.subPolygons)
  return &subpolygons_;
}
inline const ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon& PolygonLabelMulti_PolygonLabel::_internal_subpolygons(int index) const {
  return subpolygons_.Get(index);
}
inline const ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon& PolygonLabelMulti_PolygonLabel::subpolygons(int index) const {
  // @@protoc_insertion_point(field_get:standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel.subPolygons)
  return _internal_subpolygons(index);
}
inline ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon* PolygonLabelMulti_PolygonLabel::_internal_add_subpolygons() {
  return subpolygons_.Add();
}
inline ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon* PolygonLabelMulti_PolygonLabel::add_subpolygons() {
  // @@protoc_insertion_point(field_add:standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel.subPolygons)
  return _internal_add_subpolygons();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_SubPolygon >&
PolygonLabelMulti_PolygonLabel::subpolygons() const {
  // @@protoc_insertion_point(field_list:standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel.subPolygons)
  return subpolygons_;
}

// -------------------------------------------------------------------

// PolygonLabelMulti

// repeated .standard_cyborg.proto.sc3d.PolygonLabelMulti.PolygonLabel polygonLabels = 4;
inline int PolygonLabelMulti::_internal_polygonlabels_size() const {
  return polygonlabels_.size();
}
inline int PolygonLabelMulti::polygonlabels_size() const {
  return _internal_polygonlabels_size();
}
inline void PolygonLabelMulti::clear_polygonlabels() {
  polygonlabels_.Clear();
}
inline ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel* PolygonLabelMulti::mutable_polygonlabels(int index) {
  // @@protoc_insertion_point(field_mutable:standard_cyborg.proto.sc3d.PolygonLabelMulti.polygonLabels)
  return polygonlabels_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel >*
PolygonLabelMulti::mutable_polygonlabels() {
  // @@protoc_insertion_point(field_mutable_list:standard_cyborg.proto.sc3d.PolygonLabelMulti.polygonLabels)
  return &polygonlabels_;
}
inline const ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel& PolygonLabelMulti::_internal_polygonlabels(int index) const {
  return polygonlabels_.Get(index);
}
inline const ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel& PolygonLabelMulti::polygonlabels(int index) const {
  // @@protoc_insertion_point(field_get:standard_cyborg.proto.sc3d.PolygonLabelMulti.polygonLabels)
  return _internal_polygonlabels(index);
}
inline ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel* PolygonLabelMulti::_internal_add_polygonlabels() {
  return polygonlabels_.Add();
}
inline ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel* PolygonLabelMulti::add_polygonlabels() {
  // @@protoc_insertion_point(field_add:standard_cyborg.proto.sc3d.PolygonLabelMulti.polygonLabels)
  return _internal_add_polygonlabels();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::standard_cyborg::proto::sc3d::PolygonLabelMulti_PolygonLabel >&
PolygonLabelMulti::polygonlabels() const {
  // @@protoc_insertion_point(field_list:standard_cyborg.proto.sc3d.PolygonLabelMulti.polygonLabels)
  return polygonlabels_;
}

// string scImagePath = 5;
inline void PolygonLabelMulti::clear_scimagepath() {
  scimagepath_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PolygonLabelMulti::scimagepath() const {
  // @@protoc_insertion_point(field_get:standard_cyborg.proto.sc3d.PolygonLabelMulti.scImagePath)
  return _internal_scimagepath();
}
inline void PolygonLabelMulti::set_scimagepath(const std::string& value) {
  _internal_set_scimagepath(value);
  // @@protoc_insertion_point(field_set:standard_cyborg.proto.sc3d.PolygonLabelMulti.scImagePath)
}
inline std::string* PolygonLabelMulti::mutable_scimagepath() {
  // @@protoc_insertion_point(field_mutable:standard_cyborg.proto.sc3d.PolygonLabelMulti.scImagePath)
  return _internal_mutable_scimagepath();
}
inline const std::string& PolygonLabelMulti::_internal_scimagepath() const {
  return scimagepath_.GetNoArena();
}
inline void PolygonLabelMulti::_internal_set_scimagepath(const std::string& value) {
  
  scimagepath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void PolygonLabelMulti::set_scimagepath(std::string&& value) {
  
  scimagepath_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:standard_cyborg.proto.sc3d.PolygonLabelMulti.scImagePath)
}
inline void PolygonLabelMulti::set_scimagepath(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  scimagepath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:standard_cyborg.proto.sc3d.PolygonLabelMulti.scImagePath)
}
inline void PolygonLabelMulti::set_scimagepath(const char* value, size_t size) {
  
  scimagepath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:standard_cyborg.proto.sc3d.PolygonLabelMulti.scImagePath)
}
inline std::string* PolygonLabelMulti::_internal_mutable_scimagepath() {
  
  return scimagepath_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PolygonLabelMulti::release_scimagepath() {
  // @@protoc_insertion_point(field_release:standard_cyborg.proto.sc3d.PolygonLabelMulti.scImagePath)
  
  return scimagepath_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PolygonLabelMulti::set_allocated_scimagepath(std::string* scimagepath) {
  if (scimagepath != nullptr) {
    
  } else {
    
  }
  scimagepath_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), scimagepath);
  // @@protoc_insertion_point(field_set_allocated:standard_cyborg.proto.sc3d.PolygonLabelMulti.scImagePath)
}

// .standard_cyborg.proto.sc3d.QcStatus qcStatus = 6;
inline void PolygonLabelMulti::clear_qcstatus() {
  qcstatus_ = 0;
}
inline ::standard_cyborg::proto::sc3d::QcStatus PolygonLabelMulti::_internal_qcstatus() const {
  return static_cast< ::standard_cyborg::proto::sc3d::QcStatus >(qcstatus_);
}
inline ::standard_cyborg::proto::sc3d::QcStatus PolygonLabelMulti::qcstatus() const {
  // @@protoc_insertion_point(field_get:standard_cyborg.proto.sc3d.PolygonLabelMulti.qcStatus)
  return _internal_qcstatus();
}
inline void PolygonLabelMulti::_internal_set_qcstatus(::standard_cyborg::proto::sc3d::QcStatus value) {
  
  qcstatus_ = value;
}
inline void PolygonLabelMulti::set_qcstatus(::standard_cyborg::proto::sc3d::QcStatus value) {
  _internal_set_qcstatus(value);
  // @@protoc_insertion_point(field_set:standard_cyborg.proto.sc3d.PolygonLabelMulti.qcStatus)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_standard_5fcyborg_2fproto_2fsc3d_2fpolygon_5flabel_5fmulti_2eproto
