// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: standard_cyborg/proto/sc3d/bounding_box_label.proto

#include "standard_cyborg/proto/sc3d/bounding_box_label.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_standard_5fcyborg_2fproto_2fmath_2fcore_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Vec2_standard_5fcyborg_2fproto_2fmath_2fcore_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_BoundingBoxLabel_SubBoundingBox_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto;
namespace standard_cyborg {
namespace proto {
namespace sc3d {
class BoundingBoxLabel_SubBoundingBoxDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<BoundingBoxLabel_SubBoundingBox> _instance;
} _BoundingBoxLabel_SubBoundingBox_default_instance_;
class BoundingBoxLabelDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<BoundingBoxLabel> _instance;
} _BoundingBoxLabel_default_instance_;
}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg
static void InitDefaultsscc_info_BoundingBoxLabel_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::standard_cyborg::proto::sc3d::_BoundingBoxLabel_default_instance_;
    new (ptr) ::standard_cyborg::proto::sc3d::BoundingBoxLabel();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::standard_cyborg::proto::sc3d::BoundingBoxLabel::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_BoundingBoxLabel_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_BoundingBoxLabel_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto}, {
      &scc_info_BoundingBoxLabel_SubBoundingBox_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto.base,}};

static void InitDefaultsscc_info_BoundingBoxLabel_SubBoundingBox_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::standard_cyborg::proto::sc3d::_BoundingBoxLabel_SubBoundingBox_default_instance_;
    new (ptr) ::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_BoundingBoxLabel_SubBoundingBox_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_BoundingBoxLabel_SubBoundingBox_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto}, {
      &scc_info_Vec2_standard_5fcyborg_2fproto_2fmath_2fcore_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox, topleftcorner_),
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox, bottomrightcorner_),
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox, flag_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::BoundingBoxLabel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::BoundingBoxLabel, subboundingboxes_),
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::BoundingBoxLabel, scimagepath_),
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::BoundingBoxLabel, qcstatus_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox)},
  { 8, -1, sizeof(::standard_cyborg::proto::sc3d::BoundingBoxLabel)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::standard_cyborg::proto::sc3d::_BoundingBoxLabel_SubBoundingBox_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::standard_cyborg::proto::sc3d::_BoundingBoxLabel_default_instance_),
};

const char descriptor_table_protodef_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n3standard_cyborg/proto/sc3d/bounding_bo"
  "x_label.proto\022\032standard_cyborg.proto.sc3"
  "d\032%standard_cyborg/proto/math/core.proto"
  "\032*standard_cyborg/proto/sc3d/qc_status.p"
  "roto\"\315\002\n\020BoundingBoxLabel\022U\n\020subBounding"
  "Boxes\030\002 \003(\0132;.standard_cyborg.proto.sc3d"
  ".BoundingBoxLabel.SubBoundingBox\022\023\n\013scIm"
  "agePath\030\004 \001(\t\0226\n\010qcStatus\030\013 \001(\0162$.standa"
  "rd_cyborg.proto.sc3d.QcStatus\032\224\001\n\016SubBou"
  "ndingBox\0227\n\rtopLeftCorner\030\024 \001(\0132 .standa"
  "rd_cyborg.proto.math.Vec2\022;\n\021bottomRight"
  "Corner\030\025 \001(\0132 .standard_cyborg.proto.mat"
  "h.Vec2\022\014\n\004flag\030\003 \001(\010b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto_deps[2] = {
  &::descriptor_table_standard_5fcyborg_2fproto_2fmath_2fcore_2eproto,
  &::descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fqc_5fstatus_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto_sccs[2] = {
  &scc_info_BoundingBoxLabel_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto.base,
  &scc_info_BoundingBoxLabel_SubBoundingBox_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto_once;
static bool descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto = {
  &descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto_initialized, descriptor_table_protodef_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto, "standard_cyborg/proto/sc3d/bounding_box_label.proto", 508,
  &descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto_once, descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto_sccs, descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto_deps, 2, 2,
  schemas, file_default_instances, TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto::offsets,
  file_level_metadata_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto, 2, file_level_enum_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto, file_level_service_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto), true);
namespace standard_cyborg {
namespace proto {
namespace sc3d {

// ===================================================================

void BoundingBoxLabel_SubBoundingBox::InitAsDefaultInstance() {
  ::standard_cyborg::proto::sc3d::_BoundingBoxLabel_SubBoundingBox_default_instance_._instance.get_mutable()->topleftcorner_ = const_cast< ::standard_cyborg::proto::math::Vec2*>(
      ::standard_cyborg::proto::math::Vec2::internal_default_instance());
  ::standard_cyborg::proto::sc3d::_BoundingBoxLabel_SubBoundingBox_default_instance_._instance.get_mutable()->bottomrightcorner_ = const_cast< ::standard_cyborg::proto::math::Vec2*>(
      ::standard_cyborg::proto::math::Vec2::internal_default_instance());
}
class BoundingBoxLabel_SubBoundingBox::_Internal {
 public:
  static const ::standard_cyborg::proto::math::Vec2& topleftcorner(const BoundingBoxLabel_SubBoundingBox* msg);
  static const ::standard_cyborg::proto::math::Vec2& bottomrightcorner(const BoundingBoxLabel_SubBoundingBox* msg);
};

const ::standard_cyborg::proto::math::Vec2&
BoundingBoxLabel_SubBoundingBox::_Internal::topleftcorner(const BoundingBoxLabel_SubBoundingBox* msg) {
  return *msg->topleftcorner_;
}
const ::standard_cyborg::proto::math::Vec2&
BoundingBoxLabel_SubBoundingBox::_Internal::bottomrightcorner(const BoundingBoxLabel_SubBoundingBox* msg) {
  return *msg->bottomrightcorner_;
}
void BoundingBoxLabel_SubBoundingBox::clear_topleftcorner() {
  if (GetArenaNoVirtual() == nullptr && topleftcorner_ != nullptr) {
    delete topleftcorner_;
  }
  topleftcorner_ = nullptr;
}
void BoundingBoxLabel_SubBoundingBox::clear_bottomrightcorner() {
  if (GetArenaNoVirtual() == nullptr && bottomrightcorner_ != nullptr) {
    delete bottomrightcorner_;
  }
  bottomrightcorner_ = nullptr;
}
BoundingBoxLabel_SubBoundingBox::BoundingBoxLabel_SubBoundingBox()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
}
BoundingBoxLabel_SubBoundingBox::BoundingBoxLabel_SubBoundingBox(const BoundingBoxLabel_SubBoundingBox& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_topleftcorner()) {
    topleftcorner_ = new ::standard_cyborg::proto::math::Vec2(*from.topleftcorner_);
  } else {
    topleftcorner_ = nullptr;
  }
  if (from._internal_has_bottomrightcorner()) {
    bottomrightcorner_ = new ::standard_cyborg::proto::math::Vec2(*from.bottomrightcorner_);
  } else {
    bottomrightcorner_ = nullptr;
  }
  flag_ = from.flag_;
  // @@protoc_insertion_point(copy_constructor:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
}

void BoundingBoxLabel_SubBoundingBox::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_BoundingBoxLabel_SubBoundingBox_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto.base);
  ::memset(&topleftcorner_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&flag_) -
      reinterpret_cast<char*>(&topleftcorner_)) + sizeof(flag_));
}

BoundingBoxLabel_SubBoundingBox::~BoundingBoxLabel_SubBoundingBox() {
  // @@protoc_insertion_point(destructor:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
  SharedDtor();
}

void BoundingBoxLabel_SubBoundingBox::SharedDtor() {
  if (this != internal_default_instance()) delete topleftcorner_;
  if (this != internal_default_instance()) delete bottomrightcorner_;
}

void BoundingBoxLabel_SubBoundingBox::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BoundingBoxLabel_SubBoundingBox& BoundingBoxLabel_SubBoundingBox::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_BoundingBoxLabel_SubBoundingBox_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto.base);
  return *internal_default_instance();
}


void BoundingBoxLabel_SubBoundingBox::Clear() {
// @@protoc_insertion_point(message_clear_start:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && topleftcorner_ != nullptr) {
    delete topleftcorner_;
  }
  topleftcorner_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && bottomrightcorner_ != nullptr) {
    delete bottomrightcorner_;
  }
  bottomrightcorner_ = nullptr;
  flag_ = false;
  _internal_metadata_.Clear();
}

const char* BoundingBoxLabel_SubBoundingBox::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool flag = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          flag_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .standard_cyborg.proto.math.Vec2 topLeftCorner = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr = ctx->ParseMessage(_internal_mutable_topleftcorner(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .standard_cyborg.proto.math.Vec2 bottomRightCorner = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 170)) {
          ptr = ctx->ParseMessage(_internal_mutable_bottomrightcorner(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* BoundingBoxLabel_SubBoundingBox::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool flag = 3;
  if (this->flag() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_flag(), target);
  }

  // .standard_cyborg.proto.math.Vec2 topLeftCorner = 20;
  if (this->has_topleftcorner()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        20, _Internal::topleftcorner(this), target, stream);
  }

  // .standard_cyborg.proto.math.Vec2 bottomRightCorner = 21;
  if (this->has_bottomrightcorner()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        21, _Internal::bottomrightcorner(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
  return target;
}

size_t BoundingBoxLabel_SubBoundingBox::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .standard_cyborg.proto.math.Vec2 topLeftCorner = 20;
  if (this->has_topleftcorner()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *topleftcorner_);
  }

  // .standard_cyborg.proto.math.Vec2 bottomRightCorner = 21;
  if (this->has_bottomrightcorner()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *bottomrightcorner_);
  }

  // bool flag = 3;
  if (this->flag() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BoundingBoxLabel_SubBoundingBox::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
  GOOGLE_DCHECK_NE(&from, this);
  const BoundingBoxLabel_SubBoundingBox* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<BoundingBoxLabel_SubBoundingBox>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
    MergeFrom(*source);
  }
}

void BoundingBoxLabel_SubBoundingBox::MergeFrom(const BoundingBoxLabel_SubBoundingBox& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_topleftcorner()) {
    _internal_mutable_topleftcorner()->::standard_cyborg::proto::math::Vec2::MergeFrom(from._internal_topleftcorner());
  }
  if (from.has_bottomrightcorner()) {
    _internal_mutable_bottomrightcorner()->::standard_cyborg::proto::math::Vec2::MergeFrom(from._internal_bottomrightcorner());
  }
  if (from.flag() != 0) {
    _internal_set_flag(from._internal_flag());
  }
}

void BoundingBoxLabel_SubBoundingBox::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BoundingBoxLabel_SubBoundingBox::CopyFrom(const BoundingBoxLabel_SubBoundingBox& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoundingBoxLabel_SubBoundingBox::IsInitialized() const {
  return true;
}

void BoundingBoxLabel_SubBoundingBox::InternalSwap(BoundingBoxLabel_SubBoundingBox* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(topleftcorner_, other->topleftcorner_);
  swap(bottomrightcorner_, other->bottomrightcorner_);
  swap(flag_, other->flag_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BoundingBoxLabel_SubBoundingBox::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void BoundingBoxLabel::InitAsDefaultInstance() {
}
class BoundingBoxLabel::_Internal {
 public:
};

BoundingBoxLabel::BoundingBoxLabel()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:standard_cyborg.proto.sc3d.BoundingBoxLabel)
}
BoundingBoxLabel::BoundingBoxLabel(const BoundingBoxLabel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      subboundingboxes_(from.subboundingboxes_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  scimagepath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_scimagepath().empty()) {
    scimagepath_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.scimagepath_);
  }
  qcstatus_ = from.qcstatus_;
  // @@protoc_insertion_point(copy_constructor:standard_cyborg.proto.sc3d.BoundingBoxLabel)
}

void BoundingBoxLabel::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_BoundingBoxLabel_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto.base);
  scimagepath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qcstatus_ = 0;
}

BoundingBoxLabel::~BoundingBoxLabel() {
  // @@protoc_insertion_point(destructor:standard_cyborg.proto.sc3d.BoundingBoxLabel)
  SharedDtor();
}

void BoundingBoxLabel::SharedDtor() {
  scimagepath_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void BoundingBoxLabel::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BoundingBoxLabel& BoundingBoxLabel::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_BoundingBoxLabel_standard_5fcyborg_2fproto_2fsc3d_2fbounding_5fbox_5flabel_2eproto.base);
  return *internal_default_instance();
}


void BoundingBoxLabel::Clear() {
// @@protoc_insertion_point(message_clear_start:standard_cyborg.proto.sc3d.BoundingBoxLabel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  subboundingboxes_.Clear();
  scimagepath_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qcstatus_ = 0;
  _internal_metadata_.Clear();
}

const char* BoundingBoxLabel::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox subBoundingBoxes = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_subboundingboxes(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // string scImagePath = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_scimagepath();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "standard_cyborg.proto.sc3d.BoundingBoxLabel.scImagePath"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .standard_cyborg.proto.sc3d.QcStatus qcStatus = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_qcstatus(static_cast<::standard_cyborg::proto::sc3d::QcStatus>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* BoundingBoxLabel::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:standard_cyborg.proto.sc3d.BoundingBoxLabel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox subBoundingBoxes = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_subboundingboxes_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_subboundingboxes(i), target, stream);
  }

  // string scImagePath = 4;
  if (this->scimagepath().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_scimagepath().data(), static_cast<int>(this->_internal_scimagepath().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "standard_cyborg.proto.sc3d.BoundingBoxLabel.scImagePath");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_scimagepath(), target);
  }

  // .standard_cyborg.proto.sc3d.QcStatus qcStatus = 11;
  if (this->qcstatus() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      11, this->_internal_qcstatus(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:standard_cyborg.proto.sc3d.BoundingBoxLabel)
  return target;
}

size_t BoundingBoxLabel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:standard_cyborg.proto.sc3d.BoundingBoxLabel)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .standard_cyborg.proto.sc3d.BoundingBoxLabel.SubBoundingBox subBoundingBoxes = 2;
  total_size += 1UL * this->_internal_subboundingboxes_size();
  for (const auto& msg : this->subboundingboxes_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string scImagePath = 4;
  if (this->scimagepath().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_scimagepath());
  }

  // .standard_cyborg.proto.sc3d.QcStatus qcStatus = 11;
  if (this->qcstatus() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_qcstatus());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BoundingBoxLabel::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:standard_cyborg.proto.sc3d.BoundingBoxLabel)
  GOOGLE_DCHECK_NE(&from, this);
  const BoundingBoxLabel* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<BoundingBoxLabel>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:standard_cyborg.proto.sc3d.BoundingBoxLabel)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:standard_cyborg.proto.sc3d.BoundingBoxLabel)
    MergeFrom(*source);
  }
}

void BoundingBoxLabel::MergeFrom(const BoundingBoxLabel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:standard_cyborg.proto.sc3d.BoundingBoxLabel)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  subboundingboxes_.MergeFrom(from.subboundingboxes_);
  if (from.scimagepath().size() > 0) {

    scimagepath_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.scimagepath_);
  }
  if (from.qcstatus() != 0) {
    _internal_set_qcstatus(from._internal_qcstatus());
  }
}

void BoundingBoxLabel::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:standard_cyborg.proto.sc3d.BoundingBoxLabel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BoundingBoxLabel::CopyFrom(const BoundingBoxLabel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:standard_cyborg.proto.sc3d.BoundingBoxLabel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoundingBoxLabel::IsInitialized() const {
  return true;
}

void BoundingBoxLabel::InternalSwap(BoundingBoxLabel* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  subboundingboxes_.InternalSwap(&other->subboundingboxes_);
  scimagepath_.Swap(&other->scimagepath_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(qcstatus_, other->qcstatus_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BoundingBoxLabel::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox* Arena::CreateMaybeMessage< ::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox >(Arena* arena) {
  return Arena::CreateInternal< ::standard_cyborg::proto::sc3d::BoundingBoxLabel_SubBoundingBox >(arena);
}
template<> PROTOBUF_NOINLINE ::standard_cyborg::proto::sc3d::BoundingBoxLabel* Arena::CreateMaybeMessage< ::standard_cyborg::proto::sc3d::BoundingBoxLabel >(Arena* arena) {
  return Arena::CreateInternal< ::standard_cyborg::proto::sc3d::BoundingBoxLabel >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
