// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: standard_cyborg/proto/sc3d/label_3d.proto

#include "standard_cyborg/proto/sc3d/label_3d.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_standard_5fcyborg_2fproto_2fmath_2fcore_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Vec3_standard_5fcyborg_2fproto_2fmath_2fcore_2eproto;
namespace standard_cyborg {
namespace proto {
namespace sc3d {
class Label3DDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Label3D> _instance;
} _Label3D_default_instance_;
}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg
static void InitDefaultsscc_info_Label3D_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::standard_cyborg::proto::sc3d::_Label3D_default_instance_;
    new (ptr) ::standard_cyborg::proto::sc3d::Label3D();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::standard_cyborg::proto::sc3d::Label3D::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Label3D_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_Label3D_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto}, {
      &scc_info_Vec3_standard_5fcyborg_2fproto_2fmath_2fcore_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::Label3D, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::Label3D, position3d_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::standard_cyborg::proto::sc3d::Label3D)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::standard_cyborg::proto::sc3d::_Label3D_default_instance_),
};

const char descriptor_table_protodef_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n)standard_cyborg/proto/sc3d/label_3d.pr"
  "oto\022\032standard_cyborg.proto.sc3d\032%standar"
  "d_cyborg/proto/math/core.proto\"\?\n\007Label3"
  "D\0224\n\nposition3D\030\001 \001(\0132 .standard_cyborg."
  "proto.math.Vec3b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto_deps[1] = {
  &::descriptor_table_standard_5fcyborg_2fproto_2fmath_2fcore_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto_sccs[1] = {
  &scc_info_Label3D_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto_once;
static bool descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto = {
  &descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto_initialized, descriptor_table_protodef_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto, "standard_cyborg/proto/sc3d/label_3d.proto", 183,
  &descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto_once, descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto_sccs, descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto::offsets,
  file_level_metadata_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto, 1, file_level_enum_descriptors_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto, file_level_service_descriptors_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto), true);
namespace standard_cyborg {
namespace proto {
namespace sc3d {

// ===================================================================

void Label3D::InitAsDefaultInstance() {
  ::standard_cyborg::proto::sc3d::_Label3D_default_instance_._instance.get_mutable()->position3d_ = const_cast< ::standard_cyborg::proto::math::Vec3*>(
      ::standard_cyborg::proto::math::Vec3::internal_default_instance());
}
class Label3D::_Internal {
 public:
  static const ::standard_cyborg::proto::math::Vec3& position3d(const Label3D* msg);
};

const ::standard_cyborg::proto::math::Vec3&
Label3D::_Internal::position3d(const Label3D* msg) {
  return *msg->position3d_;
}
void Label3D::clear_position3d() {
  if (GetArenaNoVirtual() == nullptr && position3d_ != nullptr) {
    delete position3d_;
  }
  position3d_ = nullptr;
}
Label3D::Label3D()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:standard_cyborg.proto.sc3d.Label3D)
}
Label3D::Label3D(const Label3D& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_position3d()) {
    position3d_ = new ::standard_cyborg::proto::math::Vec3(*from.position3d_);
  } else {
    position3d_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:standard_cyborg.proto.sc3d.Label3D)
}

void Label3D::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Label3D_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto.base);
  position3d_ = nullptr;
}

Label3D::~Label3D() {
  // @@protoc_insertion_point(destructor:standard_cyborg.proto.sc3d.Label3D)
  SharedDtor();
}

void Label3D::SharedDtor() {
  if (this != internal_default_instance()) delete position3d_;
}

void Label3D::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Label3D& Label3D::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Label3D_standard_5fcyborg_2fproto_2fsc3d_2flabel_5f3d_2eproto.base);
  return *internal_default_instance();
}


void Label3D::Clear() {
// @@protoc_insertion_point(message_clear_start:standard_cyborg.proto.sc3d.Label3D)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && position3d_ != nullptr) {
    delete position3d_;
  }
  position3d_ = nullptr;
  _internal_metadata_.Clear();
}

const char* Label3D::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .standard_cyborg.proto.math.Vec3 position3D = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_position3d(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Label3D::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:standard_cyborg.proto.sc3d.Label3D)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .standard_cyborg.proto.math.Vec3 position3D = 1;
  if (this->has_position3d()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::position3d(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:standard_cyborg.proto.sc3d.Label3D)
  return target;
}

size_t Label3D::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:standard_cyborg.proto.sc3d.Label3D)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .standard_cyborg.proto.math.Vec3 position3D = 1;
  if (this->has_position3d()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *position3d_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Label3D::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:standard_cyborg.proto.sc3d.Label3D)
  GOOGLE_DCHECK_NE(&from, this);
  const Label3D* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Label3D>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:standard_cyborg.proto.sc3d.Label3D)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:standard_cyborg.proto.sc3d.Label3D)
    MergeFrom(*source);
  }
}

void Label3D::MergeFrom(const Label3D& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:standard_cyborg.proto.sc3d.Label3D)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_position3d()) {
    _internal_mutable_position3d()->::standard_cyborg::proto::math::Vec3::MergeFrom(from._internal_position3d());
  }
}

void Label3D::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:standard_cyborg.proto.sc3d.Label3D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Label3D::CopyFrom(const Label3D& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:standard_cyborg.proto.sc3d.Label3D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Label3D::IsInitialized() const {
  return true;
}

void Label3D::InternalSwap(Label3D* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(position3d_, other->position3d_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Label3D::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::standard_cyborg::proto::sc3d::Label3D* Arena::CreateMaybeMessage< ::standard_cyborg::proto::sc3d::Label3D >(Arena* arena) {
  return Arena::CreateInternal< ::standard_cyborg::proto::sc3d::Label3D >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
