// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: standard_cyborg/proto/sc3d/point_cloud_label.proto

#include "standard_cyborg/proto/sc3d/point_cloud_label.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace standard_cyborg {
namespace proto {
namespace sc3d {
class PointCloudLabelDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PointCloudLabel> _instance;
} _PointCloudLabel_default_instance_;
}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg
static void InitDefaultsscc_info_PointCloudLabel_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::standard_cyborg::proto::sc3d::_PointCloudLabel_default_instance_;
    new (ptr) ::standard_cyborg::proto::sc3d::PointCloudLabel();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::standard_cyborg::proto::sc3d::PointCloudLabel::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PointCloudLabel_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PointCloudLabel_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::PointCloudLabel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::PointCloudLabel, indices_),
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::PointCloudLabel, qcstatus_),
  PROTOBUF_FIELD_OFFSET(::standard_cyborg::proto::sc3d::PointCloudLabel, scgeometrypath_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::standard_cyborg::proto::sc3d::PointCloudLabel)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::standard_cyborg::proto::sc3d::_PointCloudLabel_default_instance_),
};

const char descriptor_table_protodef_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n2standard_cyborg/proto/sc3d/point_cloud"
  "_label.proto\022\032standard_cyborg.proto.sc3d"
  "\032*standard_cyborg/proto/sc3d/qc_status.p"
  "roto\"r\n\017PointCloudLabel\022\017\n\007indices\030\001 \003(\005"
  "\0226\n\010qcStatus\030\013 \001(\0162$.standard_cyborg.pro"
  "to.sc3d.QcStatus\022\026\n\016scGeometryPath\030\003 \001(\t"
  "b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto_deps[1] = {
  &::descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fqc_5fstatus_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto_sccs[1] = {
  &scc_info_PointCloudLabel_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto_once;
static bool descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto = {
  &descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto_initialized, descriptor_table_protodef_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto, "standard_cyborg/proto/sc3d/point_cloud_label.proto", 248,
  &descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto_once, descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto_sccs, descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto::offsets,
  file_level_metadata_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto, 1, file_level_enum_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto, file_level_service_descriptors_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto), true);
namespace standard_cyborg {
namespace proto {
namespace sc3d {

// ===================================================================

void PointCloudLabel::InitAsDefaultInstance() {
}
class PointCloudLabel::_Internal {
 public:
};

PointCloudLabel::PointCloudLabel()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:standard_cyborg.proto.sc3d.PointCloudLabel)
}
PointCloudLabel::PointCloudLabel(const PointCloudLabel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      indices_(from.indices_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  scgeometrypath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_scgeometrypath().empty()) {
    scgeometrypath_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.scgeometrypath_);
  }
  qcstatus_ = from.qcstatus_;
  // @@protoc_insertion_point(copy_constructor:standard_cyborg.proto.sc3d.PointCloudLabel)
}

void PointCloudLabel::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PointCloudLabel_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto.base);
  scgeometrypath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qcstatus_ = 0;
}

PointCloudLabel::~PointCloudLabel() {
  // @@protoc_insertion_point(destructor:standard_cyborg.proto.sc3d.PointCloudLabel)
  SharedDtor();
}

void PointCloudLabel::SharedDtor() {
  scgeometrypath_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PointCloudLabel::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PointCloudLabel& PointCloudLabel::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PointCloudLabel_standard_5fcyborg_2fproto_2fsc3d_2fpoint_5fcloud_5flabel_2eproto.base);
  return *internal_default_instance();
}


void PointCloudLabel::Clear() {
// @@protoc_insertion_point(message_clear_start:standard_cyborg.proto.sc3d.PointCloudLabel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  indices_.Clear();
  scgeometrypath_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qcstatus_ = 0;
  _internal_metadata_.Clear();
}

const char* PointCloudLabel::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated int32 indices = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_indices(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8) {
          _internal_add_indices(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string scGeometryPath = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_scgeometrypath();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "standard_cyborg.proto.sc3d.PointCloudLabel.scGeometryPath"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .standard_cyborg.proto.sc3d.QcStatus qcStatus = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_qcstatus(static_cast<::standard_cyborg::proto::sc3d::QcStatus>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PointCloudLabel::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:standard_cyborg.proto.sc3d.PointCloudLabel)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 indices = 1;
  {
    int byte_size = _indices_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_indices(), byte_size, target);
    }
  }

  // string scGeometryPath = 3;
  if (this->scgeometrypath().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_scgeometrypath().data(), static_cast<int>(this->_internal_scgeometrypath().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "standard_cyborg.proto.sc3d.PointCloudLabel.scGeometryPath");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_scgeometrypath(), target);
  }

  // .standard_cyborg.proto.sc3d.QcStatus qcStatus = 11;
  if (this->qcstatus() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      11, this->_internal_qcstatus(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:standard_cyborg.proto.sc3d.PointCloudLabel)
  return target;
}

size_t PointCloudLabel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:standard_cyborg.proto.sc3d.PointCloudLabel)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 indices = 1;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->indices_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _indices_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string scGeometryPath = 3;
  if (this->scgeometrypath().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_scgeometrypath());
  }

  // .standard_cyborg.proto.sc3d.QcStatus qcStatus = 11;
  if (this->qcstatus() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_qcstatus());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PointCloudLabel::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:standard_cyborg.proto.sc3d.PointCloudLabel)
  GOOGLE_DCHECK_NE(&from, this);
  const PointCloudLabel* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PointCloudLabel>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:standard_cyborg.proto.sc3d.PointCloudLabel)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:standard_cyborg.proto.sc3d.PointCloudLabel)
    MergeFrom(*source);
  }
}

void PointCloudLabel::MergeFrom(const PointCloudLabel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:standard_cyborg.proto.sc3d.PointCloudLabel)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  indices_.MergeFrom(from.indices_);
  if (from.scgeometrypath().size() > 0) {

    scgeometrypath_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.scgeometrypath_);
  }
  if (from.qcstatus() != 0) {
    _internal_set_qcstatus(from._internal_qcstatus());
  }
}

void PointCloudLabel::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:standard_cyborg.proto.sc3d.PointCloudLabel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PointCloudLabel::CopyFrom(const PointCloudLabel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:standard_cyborg.proto.sc3d.PointCloudLabel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PointCloudLabel::IsInitialized() const {
  return true;
}

void PointCloudLabel::InternalSwap(PointCloudLabel* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  indices_.InternalSwap(&other->indices_);
  scgeometrypath_.Swap(&other->scgeometrypath_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(qcstatus_, other->qcstatus_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PointCloudLabel::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sc3d
}  // namespace proto
}  // namespace standard_cyborg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::standard_cyborg::proto::sc3d::PointCloudLabel* Arena::CreateMaybeMessage< ::standard_cyborg::proto::sc3d::PointCloudLabel >(Arena* arena) {
  return Arena::CreateInternal< ::standard_cyborg::proto::sc3d::PointCloudLabel >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
