target 'StandardCyborgExample' do
  platform :ios, '13.0'
  use_frameworks!

  # Pods for standard cyborg
  pod 'StandardCyborgFusion', :podspec => '../StandardCyborgFusion/StandardCyborgFusion.podspec'
  pod 'StandardCyborgUI', :podspec => '../StandardCyborgUI/StandardCyborgUI.podspec'
end

